spring:
  jpa:
    database-platform: mysql 
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    generate-ddl: false
  datasource:
    url: jdbc:mysql://localhost:3306/accounts_payment?verifyServerCertificate=false&useSSL=true
    username: jsouzadev
    password: jsouzadev@123
    driverClassName: com.mysql.cj.jdbc.Driver
    platform: mysql